import serial
import time
import tkinter as tk

#GUI setup

root =tk.Tk()
root.title("Wax Printer V1.0")
root.geometry("480x300")

frame = tk.Frame(root)
frame.pack(fill=tk.BOTH,expand=True)
frame.columnconfigure(1,weight=1)
frame.rowconfigure(1,weight=1)

root.mainloop

### WIDGETS ###


#Importing of Gcode file:

def file_read(fileName):
    with open(fileName) as f:
        content_list = f.readlines()
        return content_list

fileContents = file_read("SpecificationDesign.ngc")
fileContents = fileContents[18:] #remove the fluff generated by dxf2gcode

#remove spaces and line returns from .ngf file
fileContents = [i.replace(' ','') for i in fileContents]
fileContents = [i.replace('\n','') for i in fileContents]

endIndex = fileContents.index("F0") #get the index of the F0 stop command 
fileContents = fileContents[:endIndex+1] #remove everything after that stop command

#Format each command to a 32 bit string
for i, s in enumerate(fileContents):
    fileContents[i] =s.ljust(32,'\0')

#Place serial definitions here: 

port = 'COM8'
baud = 115200
bytes =8
time=2

ser = serial.Serial(port=port,baudrate =baud,bytesize=bytes,timeout=time,stopbits=serial.STOPBITS_ONE,parity=serial.PARITY_NONE,)

# while(1):



#     if(ser.in_waiting>0):
#         serialString =ser.readline()

#         print(serialString.decode('utf-8'))

#         ser.write(b"Hello")
